from pydantic import BaseModel, Field
from crewai import Agent, Task, Crew, LLM
from dotenv import load_dotenv
from crewai_tools import CodeInterpreterTool, FileReadTool
from crewai.process import Process

import glob
import os

load_dotenv()

llm = LLM(model="gpt-4o-mini", temperature=0.6)

class QueryAnalysis(BaseModel):
    symbol: str = Field(..., description="The stock ticker symbol to analyze")
    timeframe: str = Field(..., description="Time period (e.g., '1d', '1mo', '1y').")
    action: str = Field(..., description="The action to take (e.g., 'fetch', 'plot' etc).")


query_parser_agent = Agent(
    role='Stock Data Analyst',
    goal='Parse user query and extract stock details and fetch required data from this user query: {query}',
    backstory='You are a financial analyst with expertise in stock market data retrieval and analysis. You are given a user query and your task is to parse the query and extract the stock details and the action to be taken.',
    verbose=True,
    llm=llm,   
)

query_parser_task = Task(
    description='Analyze user query and extract stock details and fetch required data from this user query: {query}',
    agent=query_parser_agent,
    expected_output="A dictionary with keys: 'symbol', 'timeframe', 'action'.",
    output_pydantic=QueryAnalysis,
    llm=llm,
)

code_writing_agent = Agent(
    role='Python Developer',
    goal='Write a python code to visualize the stock data.',
    backstory='You are a very experienced python developer specializing in stock market data visualization. You are also a Pandas, Matplotlib and yfinance library expert. You are skilled at writing production-ready python code.',
    verbose=True,
    llm=llm
)

code_writing_task = Task(
    description='''Write a python code to visualize the stock data, based on the inputs of stock analyst, 
    where you will find stock symbol, timeframe and action to be performed.''',
    agent=code_writing_agent,
    expected_output="A clean and executable python script file (.py) that will be used to visualize the stock data.",
    llm=llm
)

code_interpreter_tool = CodeInterpreterTool()

code_executing_agent = Agent(
    role='Code Execution Expert',
    goal='Review and execute the python code generated by code_writing_agent to visualize the stock data. Fix errors that you encounter. You can delegate tasks to code writing agent if needed.',
    backstory='You are skilled at executing python code and fixing errors.',
    tools=[code_interpreter_tool],
    allow_delegation=True,
    llm=llm, 
    verbose=True
)
code_executing_task = Task(
    description='Execute the python code generated by code_writing_agent to visualize the stock data. Fix errors that you encounter.',
    agent=code_executing_agent,
    expected_output="A clean and executable python script file (.py) that will be used to visualize the stock data.",
    llm=llm
)


def run_financial_analysis(query: str):
    crew = Crew(
        agents=[query_parser_agent, code_writing_agent, code_executing_agent],
        tasks=[query_parser_task, code_writing_task, code_executing_task],
        process=Process.sequential,
    )
    result = crew.kickoff(inputs={"query": query})

    return result.raw

if __name__ == "__main__":
    query = "Plot YTD stock gain of Google"
    result = run_financial_analysis(query)
    print(result)

